### ISSUE TITLE
MAC example 

### ISSUE THREAD

**Issue by fluffy** [jariarkko/core-dev-urn#4]
Is this example correct?

urn:dev:mac:0024befffe804ff1  

I sort of expected 6 bytes not 8 for MAC

**Comment by jariarkko** [comment]
Eui-48 vs. -64? But needs checking. I can’t remember off -hand.

**Comment by jariarkko** [comment]
I checked. It is correct in number of bytes (there's a translation from MAC-48 to EUI-64 that requires adding 2 bytes), but if the value represents a MAC address the inserted bytes should be ffff not fffe. So fixed this.
